### ISSUE TITLE
Possible Bug: Unable to make a hidden quest

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/StandardQuestingPack#3]
I'd like to add in hidden quests that trigger console commands and are autoClaim true but when I set the isSilent =  true, hit done, and go back into Advanced it reverts to false.  Is this only available for certain quest types or a bug with the isSilent function?

**Comment by Funwayguy** [comment]
This also appears to be a bug with a missing save/load handler for isSilent

**Comment by Funwayguy** [comment]
Just heads up but I've fixed this for the next release. Seems I made a typo and accidentally made it "isSlient" instead of "isSilent"

**Comment by Drethic** [comment]
I've confirmed the Better Questing 1.0.17 has fixed the issue with alerting the user the quest completed.  Would an option to hide the quest icon from view be part of Core or this Expansion?  The isSilent seems to only prevent the completion alert from sounding but the quest icon still appears when not in edit mode.

**Comment by Funwayguy** [comment]
Just remove the quest from the questline. Unlike HQM, Better Questing quests do not require a parent questline to function.
